# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright © 2018 Corporation for Digital Scholarship

[package]
name = "citeproc"
version = "0.0.1"
authors = ["Cormac Relf <web@cormacrelf.net>"]
license = "MPL-2.0"
edition = "2018"

[lib]
crate-type = ["rlib", "staticlib"]

[features]
test = []
default = ["cli", "parallel"]
parallel = ["rayon"]
cli = ["clap", "directories"]

[dependencies]
csl = { path = "../csl" }
pandoc_types = { path = "../pandoc-types" }
cfg-if = "0.1.9"
codespan = { version = "0.3.0", optional = false }
codespan-reporting = { version = "0.3.0", optional = false }
serde = { version = "1.0.98", features = ["rc"] }
serde_derive = "1.0.98"
serde_json = "1.0.40"
fnv = "1.0.6"
salsa = "0.12.3"

clap = { version = "2.33.0", optional = true }
rayon = { version = "1.1.0", optional = true }
directories = { version = "2.0.1", optional = true }
atty = "0.2.12"
log = "0.4.7"
parking_lot = "0.9.0"
citeproc-io = { path = "../citeproc-io" }
citeproc-proc = { path = "../citeproc-proc" }

[dev-dependencies]
test_utils = { path = "../test-utils" }
criterion = "0.2.11"
datatest = "0.4.2"
pretty_assertions = "0.6.1"
lazy_static = "1.3.0"
serde_yaml = "0.8.9"

# [[bench]]
# name = "some"
# harness = false

