language: rust
sudo: false

cache: cargo

# https://bors.tech/documentation/getting-started/
branches:
  only:
    # This is where pull requests from "bors r+" are built.
    - staging
    # This is where pull requests from "bors try" are built.
    - trying
    # Uncomment this to enable building pull requests.
    - master

matrix:
  include:
  - rust: nightly
    before_script:
      - pip install --user awscli
      - mkdir -p .snapshots/branches
      - aws s3 cp s3://citeproc-rs-test-results/.snapshots/branches/master .snapshots/branches/master

    script:
      # check for regressions
      # travis doesn't set HEAD to a branch
      # 'diff' always succeeds on master branch, as those refs are identical
      - cargo pull-locales
      - cargo test-suite store
      - cp .snapshots/current .snapshots/branches/$TRAVIS_BRANCH
      - cargo test-suite diff master..current

    addons:
      artifacts:
        s3_region: "ap-southeast-2"
        paths:
          # artifacts only run on master
          - .snapshots/commits/$TRAVIS_COMMIT
        target_paths:
          - /
        debug: true

  # new stage, so only runs if the previous one succeeded
  - stage: wasm-deploy
    rust: nightly
    env: RUST_BACKTRACE=1
    # addons:
    #   firefox: latest
      # chrome: stable
    before_script:
      - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f
    script:
      - (cd crates/wasm/js-demo && yarn && yarn build)
      # - cargo test --all
      # - (cd wasm && wasm-pack build)
      # - (cd wasm && wasm-pack test --firefox --headless)

    deploy:
      provider: pages
      skip_cleanup: true
      local_dir: "crates/wasm/js-demo/dist/"
      repo: "cormacrelf/wasm-demo"
      github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
      on:
        branch: master

