[package]
name = "citeproc"
version = "0.0.1"
authors = ["Cormac Relf <web@cormacrelf.net>"]
edition = "2018"

[dependencies]
roxmltree = "0.3.0"
clap = "*"
codespan = "0.2.0"
codespan-reporting = "0.2.0"
strum = "0.11.0"
strum_macros = "0.11.0"
