# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright © 2018 Corporation for Digital Scholarship

[workspace]
members = [ "crates/*" ]
default-members = [ "crates/citeproc-proc", "crates/citeproc", "crates/csl", "crates/citeproc-db", "crates/citeproc-io" ]

[profile.bench]
lto = "thin"

[profile.release]
lto = "thin"

# [profile.dev]
# rpath = true
