# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright © 2018 Corporation for Digital Scholarship

unstable_features = true

ignore = [
  "citeproc/src/input/unicode/script.rs",
]

# report_todo = "Unnumbered"
# report_fixme = "Unnumbered"
# struct_field_align_threshold = 20
# overflow_delimited_expr = true
