[package]
name = "test_utils"
version = "0.1.0"
authors = ["Cormac Relf <web@cormacrelf.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
citeproc = { path = "../citeproc", features = ["test"] }
citeproc-io = { path = "../citeproc-io" }
csl = { path = "../csl" }
directories = "2.0.2"
lazy_static = "1.3.0"
serde_derive = "1.0.99"
serde = "1.0.99"
serde_json = "1.0.40"
serde_yaml = "0.8.9"
nom = "5.0.1"
regex = "1.2.1"
