[package]
name = "citeproc"
version = "0.0.1"
authors = ["Cormac Relf <web@cormacrelf.net>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "citeproc-rs"
path = "src/main.rs"
# required-features = ["cli"]

[features]
default = []
flame_it = ["flame", "flamer"]
thread = []
# cli = ["clap"]

[dependencies]
roxmltree = "0.3.0"
clap = { version = "2.32.0", optional = false }
codespan = { version = "0.2.0", optional = false }
codespan-reporting = { version = "0.2.0", optional = false }
strum = "0.11.0"
strum_macros = "0.11.0"
cfg-if = "0.1.2"
typed-arena = "1.4.1"
pandoc_types = "0.2"
serde_derive = "1.0.80"
serde = "1.0.80"
serde_json = "1.0.33"

flame = { version = "0.2.2", optional = true }
flamer = { version = "0.3", optional = true }
fnv = "1.0.6"
nom = "3"
