name:                pandoc-preproc
version:             0.1.0.0
github:              "cormacrelf/citeproc-rs"
license:             BSD3
author:              "Cormac Relf"
maintainer:          "web@cormacrelf.net"
copyright:           "2019 Cormac Relf"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/pandoc-preproc#readme>

dependencies:
- base >= 4.7 && < 5
- pandoc >= 2.6 && < 3
- pandoc-types >= 1.17.5.4 && < 1.18
- aeson
- lens
- lens-aeson
- bytestring
- text
- data-default
- containers
- vector

library:
  source-dirs: src

executables:
  pandoc-preproc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pandoc-preproc

tests:
  pandoc-preproc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pandoc-preproc
